
create table if not exists imagen (id bigint generated by default as identity, data_atualizacao timestamp, dados blob, descricao varchar(255), tipo varchar(255), primary key (id) );
create table if not exists usuario ( id bigint generated by default as identity, data_atualizacao timestamp, login varchar(255), nome varchar(255), senha varchar(255), imagen_id bigint, primary key (id), foreign key (imagen_id) references imagen );
