
package br.com.knight.estoque.servico;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "autores", targetNamespace = "http://servico.estoque.knight.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Autores {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.knight.estoque.servico.Autor>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarAutores", targetNamespace = "http://servico.estoque.knight.com.br/", className = "br.com.knight.estoque.servico.ListarAutores")
    @ResponseWrapper(localName = "listarAutoresResponse", targetNamespace = "http://servico.estoque.knight.com.br/", className = "br.com.knight.estoque.servico.ListarAutoresResponse")
    public List<Autor> listarAutores();

}
