
package br.com.knight.estoque.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "autores", targetNamespace = "http://servico.estoque.knight.com.br/", wsdlLocation = "http://localhost:8080/autores?wsdl")
public class Autores_Service
    extends Service
{

    private final static URL AUTORES_WSDL_LOCATION;
    private final static WebServiceException AUTORES_EXCEPTION;
    private final static QName AUTORES_QNAME = new QName("http://servico.estoque.knight.com.br/", "autores");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/autores?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTORES_WSDL_LOCATION = url;
        AUTORES_EXCEPTION = e;
    }

    public Autores_Service() {
        super(__getWsdlLocation(), AUTORES_QNAME);
    }

    public Autores_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTORES_QNAME, features);
    }

    public Autores_Service(URL wsdlLocation) {
        super(wsdlLocation, AUTORES_QNAME);
    }

    public Autores_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTORES_QNAME, features);
    }

    public Autores_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Autores_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Autores
     */
    @WebEndpoint(name = "autoresPort")
    public Autores getAutoresPort() {
        return super.getPort(new QName("http://servico.estoque.knight.com.br/", "autoresPort"), Autores.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Autores
     */
    @WebEndpoint(name = "autoresPort")
    public Autores getAutoresPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.estoque.knight.com.br/", "autoresPort"), Autores.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTORES_EXCEPTION!= null) {
            throw AUTORES_EXCEPTION;
        }
        return AUTORES_WSDL_LOCATION;
    }

}
