
package br.com.knight.estoque.servico;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ListagemLivro", targetNamespace = "http://servico.estoque.knight.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ListagemLivro {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.knight.estoque.servico.Livro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarLivros", targetNamespace = "http://servico.estoque.knight.com.br/", className = "br.com.knight.estoque.servico.ListarLivros")
    @ResponseWrapper(localName = "listarLivrosResponse", targetNamespace = "http://servico.estoque.knight.com.br/", className = "br.com.knight.estoque.servico.ListarLivrosResponse")
    public List<Livro> listarLivros();

}
