
package br.com.knight.estoque.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ListagemLivroService", targetNamespace = "http://servico.estoque.knight.com.br/", wsdlLocation = "http://localhost:8080/ListagemLivro?wsdl")
public class ListagemLivroService
    extends Service
{

    private final static URL LISTAGEMLIVROSERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTAGEMLIVROSERVICE_EXCEPTION;
    private final static QName LISTAGEMLIVROSERVICE_QNAME = new QName("http://servico.estoque.knight.com.br/", "ListagemLivroService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ListagemLivro?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTAGEMLIVROSERVICE_WSDL_LOCATION = url;
        LISTAGEMLIVROSERVICE_EXCEPTION = e;
    }

    public ListagemLivroService() {
        super(__getWsdlLocation(), LISTAGEMLIVROSERVICE_QNAME);
    }

    public ListagemLivroService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTAGEMLIVROSERVICE_QNAME, features);
    }

    public ListagemLivroService(URL wsdlLocation) {
        super(wsdlLocation, LISTAGEMLIVROSERVICE_QNAME);
    }

    public ListagemLivroService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTAGEMLIVROSERVICE_QNAME, features);
    }

    public ListagemLivroService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListagemLivroService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListagemLivro
     */
    @WebEndpoint(name = "ListagemLivroPort")
    public ListagemLivro getListagemLivroPort() {
        return super.getPort(new QName("http://servico.estoque.knight.com.br/", "ListagemLivroPort"), ListagemLivro.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListagemLivro
     */
    @WebEndpoint(name = "ListagemLivroPort")
    public ListagemLivro getListagemLivroPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.estoque.knight.com.br/", "ListagemLivroPort"), ListagemLivro.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTAGEMLIVROSERVICE_EXCEPTION!= null) {
            throw LISTAGEMLIVROSERVICE_EXCEPTION;
        }
        return LISTAGEMLIVROSERVICE_WSDL_LOCATION;
    }

}
