
package br.com.knight.estoque.servico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "livros", targetNamespace = "http://servico.estoque.knight.com.br/", wsdlLocation = "http://localhost:8080/livros?wsdl")
public class Livros_Service
    extends Service
{

    private final static URL LIVROS_WSDL_LOCATION;
    private final static WebServiceException LIVROS_EXCEPTION;
    private final static QName LIVROS_QNAME = new QName("http://servico.estoque.knight.com.br/", "livros");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/livros?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVROS_WSDL_LOCATION = url;
        LIVROS_EXCEPTION = e;
    }

    public Livros_Service() {
        super(__getWsdlLocation(), LIVROS_QNAME);
    }

    public Livros_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVROS_QNAME, features);
    }

    public Livros_Service(URL wsdlLocation) {
        super(wsdlLocation, LIVROS_QNAME);
    }

    public Livros_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIVROS_QNAME, features);
    }

    public Livros_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Livros_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Livros
     */
    @WebEndpoint(name = "livrosPort")
    public Livros getLivrosPort() {
        return super.getPort(new QName("http://servico.estoque.knight.com.br/", "livrosPort"), Livros.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Livros
     */
    @WebEndpoint(name = "livrosPort")
    public Livros getLivrosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://servico.estoque.knight.com.br/", "livrosPort"), Livros.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVROS_EXCEPTION!= null) {
            throw LIVROS_EXCEPTION;
        }
        return LIVROS_WSDL_LOCATION;
    }

}
