
package br.com.knight.estoque.servico;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LivroService", targetNamespace = "http://servico.estoque.knight.com.br/")
@XmlSeeAlso({
    br.com.knight.estoque.servico.ObjectFactory.class,
    br.com.knight.estoque.servico.excecoes.ObjectFactory.class
})
public interface LivroService {


    /**
     * 
     * @param usuario
     * @param parameters
     * @return
     *     returns br.com.knight.estoque.servico.CriarLivroResponse
     * @throws SOAPException_Exception
     * @throws UsuarioNaoAutorizadoException
     */
    @WebMethod
    @WebResult(name = "criarLivroResponse", targetNamespace = "http://servico.estoque.knight.com.br/", partName = "result")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public CriarLivroResponse criarLivro(
        @WebParam(name = "criarLivro", targetNamespace = "http://servico.estoque.knight.com.br/", partName = "parameters")
        CriarLivro parameters,
        @WebParam(name = "usuario", targetNamespace = "http://servico.estoque.knight.com.br/", header = true, partName = "usuario")
        Usuario usuario)
        throws SOAPException_Exception, UsuarioNaoAutorizadoException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.knight.estoque.servico.Livro>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarLivros", targetNamespace = "http://servico.estoque.knight.com.br/", className = "br.com.knight.estoque.servico.ListarLivros")
    @ResponseWrapper(localName = "listarLivrosResponse", targetNamespace = "http://servico.estoque.knight.com.br/", className = "br.com.knight.estoque.servico.ListarLivrosResponse")
    public List<Livro> listarLivros();

    /**
     * 
     * @param tamanhoDaPagina
     * @param numeroDaPagina
     * @return
     *     returns java.util.List<br.com.knight.estoque.servico.Livro>
     */
    @WebMethod
    @WebResult(name = "livro", targetNamespace = "")
    @RequestWrapper(localName = "listarLivrosPaginacao", targetNamespace = "http://servico.estoque.knight.com.br/", className = "br.com.knight.estoque.servico.ListarLivrosPaginacao")
    @ResponseWrapper(localName = "listarLivrosPaginacaoResponse", targetNamespace = "http://servico.estoque.knight.com.br/", className = "br.com.knight.estoque.servico.ListarLivrosPaginacaoResponse")
    public List<Livro> listarLivrosPaginacao(
        @WebParam(name = "numeroDaPagina", targetNamespace = "")
        int numeroDaPagina,
        @WebParam(name = "tamanhoDaPagina", targetNamespace = "")
        int tamanhoDaPagina);

}
