
package br.com.knight.estoque.servico;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UsuarioNaoAutorizado", targetNamespace = "http://servico.estoque.knight.com.br/excecoes/")
public class UsuarioNaoAutorizadoException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioFaultInfo faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioNaoAutorizadoException(String message, UsuarioFaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UsuarioNaoAutorizadoException(String message, UsuarioFaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.knight.estoque.servico.UsuarioFaultInfo
     */
    public UsuarioFaultInfo getFaultInfo() {
        return faultInfo;
    }

}
