
package br.com.knight.estoque.servico;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "UsuarioNaoAutorizadoException", targetNamespace = "http://servico.estoque.knight.com.br/")
public class UsuarioNaoAutorizadoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioNaoAutorizadoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioNaoAutorizadoException_Exception(String message, UsuarioNaoAutorizadoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public UsuarioNaoAutorizadoException_Exception(String message, UsuarioNaoAutorizadoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.knight.estoque.servico.UsuarioNaoAutorizadoException
     */
    public UsuarioNaoAutorizadoException getFaultInfo() {
        return faultInfo;
    }

}
